apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-user-env
data:
  VAULT_URL: "http://vault.default.svc.cluster.local:8200"
  VAULT_SECRET_PATH: "secret/data/grafana/users"
  GRAFANA_URL: "http://grafana.default.svc.cluster.local:3000"
