apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: grafana-user-secrets
    creationPolicy: Merge
  data:
    - secretKey: GRAFANA_ADMIN_TOKEN
      remoteRef:
        key: secret/data/grafana
        property: admin_token
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/grafana
        property: admin_password
