apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vault-access-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["grafana-user-secrets"] # Restrict to specific secret
    verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: vault-access-binding
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: default
roleRef:
  kind: Role
  name: vault-access-role
  apiGroup: rbac.authorization.k8s.io

